services:
  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs
    restart: unless-stopped
    # ports:
    # - 9000:9000
    # - 9001:9001
    volumes:
      - rustfs_data:/data
    networks:
      - nginx
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}
    command: --access-key admin --secret-key admin /data

volumes:
  rustfs_data:

networks:
  nginx:
    external: true
