services:
  databasus:
    container_name: databasus
    image: databasus/databasus:${VERSION}
    # ports:
    # - "4005:4005"
    volumes:
      - /home/afaqjaved/docker-volumes/databasus/databasus-data:/databasus-data
    restart: unless-stopped
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_INSECURE_SKIP_VERIFY: ${SMTP_INSECURE_SKIP_VERIFY}
      DATABASUS_URL: ${DATABASUS_URL}
    networks:
      - nginx
      - shared_postgres
    healthcheck:
      test: ["CMD", "databasus", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

networks:
  nginx:
    external: true
  shared_postgres:
    external: true
