services:
  portabase:
    image: portabase/portabase:${VERSION}
    restart: unless-stopped
    # ports:
    # - "8887:80"
    environment:
      PROJECT_URL: ${PROJECT_URL}
      PROJECT_SECRET: ${PROJECT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      AUTH_DEFAULT_USER_NAME: ${AUTH_DEFAULT_USER_NAME}
      AUTH_DEFAULT_USER: ${AUTH_DEFAULT_USER}
      AUTH_DEFAULT_PASSWORD: ${AUTH_DEFAULT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - portabase:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nginx
      - shared_postgres

volumes:
  portabase:

networks:
  nginx:
    external: true
  shared_postgres:
    external: true
