services:
  postgresVector:
    build: .
    container_name: pgvector-db
    networks:
      - nginx
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    # ports:
    # - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: # Stores data outside the container to ensure persistence

networks:
  nginx:
    external: true
