services:
  surrealdb:
    image: surrealdb/surrealdb:v2
    command: start --log ${SURREAL_LOG_LEVEL} --user ${SURREAL_USER} --pass ${SURREAL_PASSWORD} ${SURREAL_DB_PATH}
    user: root
    ports:
      - "${SURREAL_PORT}:8000"
    volumes:
      - ${DB_VOLUME_PATH}:/mydata
    networks:
      - open_notebook_internal
      - nginx_proxy
    restart: always

  open_notebook:
    image: lfnovo/open_notebook:v1-latest
    ports:
      - "${NOTEBOOK_UI_PORT}:8502"
      - "${NOTEBOOK_API_PORT}:5055"
    env_file:
      - variables.env
    environment:
      - OPEN_NOTEBOOK_ENCRYPTION_KEY=${OPEN_NOTEBOOK_ENCRYPTION_KEY}
      - SURREAL_URL=${SURREAL_URL}
      - SURREAL_USER=${SURREAL_USER}
      - SURREAL_PASSWORD=${SURREAL_PASSWORD}
      - SURREAL_NAMESPACE=${SURREAL_NAMESPACE}
      - SURREAL_DATABASE=${SURREAL_DATABASE}
    volumes:
      - ${NOTEBOOK_VOLUME_PATH}:/app/data
    depends_on:
      - surrealdb
    networks:
      - open_notebook_internal
      - nginx_proxy
    restart: always

networks:
  open_notebook_internal:
    driver: bridge
  nginx_proxy:
    external: true
