version: '3.8'

services:
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    # ports:
    #   - "9000:9000" # will be exposed using Nginx Proxy Manager (npm)
    #   - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_DATA_PATH}:/data
    command: server /data --console-address ":9001"
    networks:
      - nginx

networks:
  nginx:
    external : true
