services:
  dash:
    image: mauricenino/dashdot:latest
    restart: unless-stopped
    privileged: true
    #ports:
    #  - '80:3001'
    volumes:
      - /:/mnt/host:ro
    networks:
      - nginx
    environment:
      DASHDOT_WIDGET_LIST: 'os,cpu,storage,ram,network'

networks:
  nginx:
    external: true